source("https://bioconductor.org/biocLite.R")
biocLite("ChIPQC")
biocLite("TxDb.Hsapiens.UCSC.hg38.knownGene")
biocLite("DiffBind")
biocLite("ChIPseeker")
biocLite("GenomicRanges")
biocLite("chipenrich")
biocLite("ChIPpeakAnno")
biocLite("rGREAT")
biocLite("DiffBind")
biocLite("Rcade")
biocLite("DiffHiC")
biocLite("biomaRt")
require(devtools)
devtools::install_github('hms-dbmi/spp', build_vignettes = FALSE)